# Generated by Django 5.1.4 on 2024-12-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petitioners',
            fields=[
                ('petitioner_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('password_hash', models.TextField()),
                ('bioid', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'petitioners',
                'managed': False,
            },
        ),
    ]
