# Generated by Django 5.1.4 on 2024-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'petition_signatures',
                'managed': False,
            },
        ),
    ]
