# Generated by Django 5.1.4 on 2024-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioID',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bioid',
            },
        ),
    ]
