# Generated by Django 5.1.4 on 2024-12-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioid',
            options={'managed': False},
        ),
    ]
