# Generated by Django 5.1.4 on 2024-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_alter_bioid_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('petition_id', models.AutoField(primary_key=True, serialize=False)),
                ('petitioner_email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=45)),
                ('response', models.TextField(blank=True, null=True)),
                ('signature_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'petitions',
                'managed': False,
            },
        ),
    ]
