# Generated by Django 5.1.4 on 2024-12-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_petition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_threshold', models.IntegerField(default=100)),
                ('admin_email', models.EmailField(default='admin@petition.parliament.sr', max_length=254)),
                ('password_hash', models.TextField()),
            ],
            options={
                'db_table': 'admin_settings',
                'managed': False,
            },
        ),
    ]
